apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
spec:
  selector:
    matchLabels:
      run: rest-api
  replicas: 4
  template:
    metadata:
      labels:
        run: restapi
    spec:
      containers:
      - name: rest-api
        image: gcr.io/rdrtest/flaskweb:latest
        ports:
        - containerPort: 8800
---
apiVersion: v1
kind: Service
metadata:
  name: rest-api
  labels:
    run: rest-api
spec:
  ports:
  - port: 8800
    protocol: TCP
  type: LoadBalancer
  selector:
    run: rest-api
